/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sudoku;

import java.awt.Button;
import java.awt.Event;
import java.awt.Image;
import java.awt.List;
import static java.awt.SystemColor.window;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.beans.EventHandler;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URL;
import java.util.ArrayList;
import java.util.Random;
import java.util.TimerTask;
import static javafx.scene.input.KeyCode.R;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.text.View;

/**
 *
 * @author whxf
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        InitPicBox(); //用来初始化所有的PictureBox控件
        InitNumber_c();//用来初始化number_c数组
        InitNumber_o();//用来初始化number_o数组
        InitButton();//用来初始化所有的Button控件
        InitButtonH();//用来初始化ButtonH图片数组
        InitButtonO();//用来初始化ButtonO图片数组
        InitEasyQ();//初始化简单题目
        InitMediumQ();//初始化中等题目
        InitHardQ();//初始化难题
        InitLabel();//将一些图片加载到内存
        blocksAddListener();//label的各种点击事件an
        //InitTestQ();//测试用题目
        //this.getContentPane().setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        button5 = new javax.swing.JLabel();
        button6 = new javax.swing.JLabel();
        button4 = new javax.swing.JLabel();
        button7 = new javax.swing.JLabel();
        button8 = new javax.swing.JLabel();
        button9 = new javax.swing.JLabel();
        button1 = new javax.swing.JLabel();
        button2 = new javax.swing.JLabel();
        button3 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        replayButton = new javax.swing.JButton();
        checkLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        label21 = new javax.swing.JLabel();
        label74 = new javax.swing.JLabel();
        label14 = new javax.swing.JLabel();
        label38 = new javax.swing.JLabel();
        label65 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        label46 = new javax.swing.JLabel();
        label39 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label28 = new javax.swing.JLabel();
        label12 = new javax.swing.JLabel();
        label45 = new javax.swing.JLabel();
        label31 = new javax.swing.JLabel();
        label52 = new javax.swing.JLabel();
        label42 = new javax.swing.JLabel();
        label26 = new javax.swing.JLabel();
        label11 = new javax.swing.JLabel();
        label40 = new javax.swing.JLabel();
        label48 = new javax.swing.JLabel();
        label27 = new javax.swing.JLabel();
        label62 = new javax.swing.JLabel();
        label50 = new javax.swing.JLabel();
        label81 = new javax.swing.JLabel();
        label68 = new javax.swing.JLabel();
        label70 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label16 = new javax.swing.JLabel();
        label57 = new javax.swing.JLabel();
        label64 = new javax.swing.JLabel();
        label33 = new javax.swing.JLabel();
        label17 = new javax.swing.JLabel();
        label75 = new javax.swing.JLabel();
        label79 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label66 = new javax.swing.JLabel();
        label80 = new javax.swing.JLabel();
        label60 = new javax.swing.JLabel();
        label54 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        label56 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label67 = new javax.swing.JLabel();
        label37 = new javax.swing.JLabel();
        label43 = new javax.swing.JLabel();
        label72 = new javax.swing.JLabel();
        label20 = new javax.swing.JLabel();
        label47 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label71 = new javax.swing.JLabel();
        label10 = new javax.swing.JLabel();
        label13 = new javax.swing.JLabel();
        label44 = new javax.swing.JLabel();
        label35 = new javax.swing.JLabel();
        label29 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        label51 = new javax.swing.JLabel();
        label69 = new javax.swing.JLabel();
        label36 = new javax.swing.JLabel();
        label22 = new javax.swing.JLabel();
        label19 = new javax.swing.JLabel();
        label34 = new javax.swing.JLabel();
        label78 = new javax.swing.JLabel();
        label23 = new javax.swing.JLabel();
        label41 = new javax.swing.JLabel();
        label73 = new javax.swing.JLabel();
        label53 = new javax.swing.JLabel();
        label15 = new javax.swing.JLabel();
        label58 = new javax.swing.JLabel();
        label77 = new javax.swing.JLabel();
        label63 = new javax.swing.JLabel();
        label32 = new javax.swing.JLabel();
        label76 = new javax.swing.JLabel();
        label18 = new javax.swing.JLabel();
        label25 = new javax.swing.JLabel();
        label49 = new javax.swing.JLabel();
        label30 = new javax.swing.JLabel();
        label61 = new javax.swing.JLabel();
        label59 = new javax.swing.JLabel();
        label55 = new javax.swing.JLabel();
        label24 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("数独");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        button5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5_b.png"))); // NOI18N
        button5.setText("jLabel82");

        button6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/6_b.png"))); // NOI18N
        button6.setText("jLabel82");

        button4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/4_b.png"))); // NOI18N
        button4.setText("jLabel82");

        button7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/7_b.png"))); // NOI18N
        button7.setText("jLabel82");

        button8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/8_b.png"))); // NOI18N
        button8.setText("jLabel82");

        button9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/9_b.png"))); // NOI18N
        button9.setText("jLabel82");

        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/1_b.png"))); // NOI18N
        button1.setText("jLabel82");

        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/2_b.png"))); // NOI18N
        button2.setText("jLabel82");

        button3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/3_b.png"))); // NOI18N
        button3.setText("jLabel82");

        deleteButton.setText("清除");
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });

        replayButton.setText("重做");
        replayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                replayButtonMouseClicked(evt);
            }
        });

        checkLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/correct.png"))); // NOI18N
        checkLabel.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(deleteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(replayButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(checkLabel)))
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(checkLabel)
                .addGap(18, 18, 18)
                .addComponent(replayButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteButton)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button3)
                    .addComponent(button2)
                    .addComponent(button1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button6)
                    .addComponent(button5)
                    .addComponent(button4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button9)
                    .addComponent(button8)
                    .addComponent(button7))
                .addGap(50, 50, 50))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        label21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label21.setText("jLabel1");

        label74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_w.png"))); // NOI18N
        label74.setText("jLabel1");

        label14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_w.png"))); // NOI18N
        label14.setText("jLabel1");

        label38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label38.setText("jLabel1");

        label65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_w.png"))); // NOI18N
        label65.setText("jLabel1");

        label8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label8.setText("jLabel1");

        label46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_w.png"))); // NOI18N
        label46.setText("jLabel1");

        label39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label39.setText("jLabel1");

        label5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_w.png"))); // NOI18N
        label5.setText("jLabel1");

        label28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label28.setText("jLabel1");

        label12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label12.setText("jLabel1");

        label45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label45.setText("jLabel1");

        label31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label31.setText("jLabel1");

        label52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label52.setText("jLabel1");

        label42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label42.setText("jLabel1");

        label26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label26.setText("jLabel1");

        label11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label11.setText("jLabel1");

        label40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label40.setText("jLabel1");

        label48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label48.setText("jLabel1");

        label27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label27.setText("jLabel1");

        label62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_w.png"))); // NOI18N
        label62.setText("jLabel1");

        label50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label50.setText("jLabel1");

        label81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_w.png"))); // NOI18N
        label81.setText("jLabel1");

        label68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label68.setText("jLabel1");

        label70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_w.png"))); // NOI18N
        label70.setText("jLabel1");

        label7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label7.setText("jLabel1");

        label16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label16.setText("jLabel1");

        label57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label57.setText("jLabel1");

        label64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_w.png"))); // NOI18N
        label64.setText("jLabel1");

        label33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label33.setText("jLabel1");

        label17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label17.setText("jLabel1");

        label75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_w.png"))); // NOI18N
        label75.setText("jLabel1");

        label79.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_w.png"))); // NOI18N
        label79.setText("jLabel1");

        label2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label2.setText("jLabel1");

        label66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_w.png"))); // NOI18N
        label66.setText("jLabel1");

        label80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_w.png"))); // NOI18N
        label80.setText("jLabel1");

        label60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label60.setText("jLabel1");

        label54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_w.png"))); // NOI18N
        label54.setText("jLabel1");

        label6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_w.png"))); // NOI18N
        label6.setText("jLabel1");

        label56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_w.png"))); // NOI18N
        label56.setText("jLabel1");

        label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_w.png"))); // NOI18N
        label1.setText("jLabel1");

        label67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label67.setText("jLabel1");

        label37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label37.setText("jLabel1");

        label43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label43.setText("jLabel1");

        label72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_w.png"))); // NOI18N
        label72.setText("jLabel1");

        label20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label20.setText("jLabel1");

        label47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label47.setText("jLabel1");

        label4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_w.png"))); // NOI18N
        label4.setText("jLabel1");

        label3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label3.setText("jLabel1");

        label71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_w.png"))); // NOI18N
        label71.setText("jLabel1");

        label10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label10.setText("jLabel1");

        label13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label13.setText("jLabel1");

        label44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label44.setText("jLabel1");

        label35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label35.setText("jLabel1");

        label29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label29.setText("jLabel1");

        label9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_w.png"))); // NOI18N
        label9.setText("jLabel1");

        label51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label51.setText("jLabel1");

        label69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label69.setText("jLabel1");

        label36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label36.setText("jLabel1");

        label22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label22.setText("jLabel1");

        label19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label19.setText("jLabel1");

        label34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label34.setText("jLabel1");

        label78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_w.png"))); // NOI18N
        label78.setText("jLabel1");

        label23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label23.setText("jLabel1");

        label41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label41.setText("jLabel1");

        label73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_w.png"))); // NOI18N
        label73.setText("jLabel1");

        label53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label53.setText("jLabel1");

        label15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label15.setText("jLabel1");

        label58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label58.setText("jLabel1");

        label77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label77.setText("jLabel1");

        label63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_w.png"))); // NOI18N
        label63.setText("jLabel1");

        label32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label32.setText("jLabel1");

        label76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_w.png"))); // NOI18N
        label76.setText("jLabel1");

        label18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label18.setText("jLabel1");

        label25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label25.setText("jLabel1");

        label49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label49.setText("jLabel1");

        label30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label30.setText("jLabel1");

        label61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label61.setText("jLabel1");

        label59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label59.setText("jLabel1");

        label55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_w.png"))); // NOI18N
        label55.setText("jLabel1");

        label24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_r.png"))); // NOI18N
        label24.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label73, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label74, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label75, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label76, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label77, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label78, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label79, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label80, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label81, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label64, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label65, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label66, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label67, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label68, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label69, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label70, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label71, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label72, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label55, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label56, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label57, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label58, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label59, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label60, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label61, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label62, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label63, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label46, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label47, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label48, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(label49, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label50, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label51, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(label52, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label53, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label54, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label37, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label38, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label39, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(label40, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label41, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label42, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(label43, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label44, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label45, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label28, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label29, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label30, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(label31, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label32, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label33, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(label34, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label35, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label36, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(label25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label26, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2)
                    .addComponent(label3)
                    .addComponent(label4)
                    .addComponent(label5)
                    .addComponent(label6)
                    .addComponent(label7)
                    .addComponent(label8)
                    .addComponent(label9)
                    .addComponent(label1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label11)
                    .addComponent(label12)
                    .addComponent(label13)
                    .addComponent(label14)
                    .addComponent(label15)
                    .addComponent(label16)
                    .addComponent(label17)
                    .addComponent(label18)
                    .addComponent(label10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label20)
                    .addComponent(label21)
                    .addComponent(label22)
                    .addComponent(label23)
                    .addComponent(label24)
                    .addComponent(label25)
                    .addComponent(label26)
                    .addComponent(label27)
                    .addComponent(label19))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label29)
                    .addComponent(label30)
                    .addComponent(label31)
                    .addComponent(label32)
                    .addComponent(label33)
                    .addComponent(label34)
                    .addComponent(label35)
                    .addComponent(label36)
                    .addComponent(label28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label38)
                    .addComponent(label39)
                    .addComponent(label40)
                    .addComponent(label41)
                    .addComponent(label42)
                    .addComponent(label43)
                    .addComponent(label44)
                    .addComponent(label45)
                    .addComponent(label37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label47)
                    .addComponent(label48)
                    .addComponent(label49)
                    .addComponent(label50)
                    .addComponent(label51)
                    .addComponent(label52)
                    .addComponent(label53)
                    .addComponent(label54)
                    .addComponent(label46))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label56)
                    .addComponent(label57)
                    .addComponent(label58)
                    .addComponent(label59)
                    .addComponent(label60)
                    .addComponent(label61)
                    .addComponent(label62)
                    .addComponent(label63)
                    .addComponent(label55))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label65)
                    .addComponent(label66)
                    .addComponent(label67)
                    .addComponent(label68)
                    .addComponent(label69)
                    .addComponent(label70)
                    .addComponent(label71)
                    .addComponent(label72)
                    .addComponent(label64))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label74)
                    .addComponent(label75)
                    .addComponent(label76)
                    .addComponent(label77)
                    .addComponent(label78)
                    .addComponent(label79)
                    .addComponent(label80)
                    .addComponent(label81)
                    .addComponent(label73))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("开始游戏");

        jMenuItem1.setText("易");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("中");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("难");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("帮助");

        jMenuItem5.setText("游戏说明");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //加载游戏说明的窗口
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        Frame1 frame = new Frame1();
        frame.setVisible(true);
        frame.validate();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    //加载简单题目
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Random ra = new Random();
        int len = Easy.size();
        if (len != 0) {
            int choice = ra.nextInt(1000000) % len;
            int cnt = 0;
            int i = 0;
            String tmp = Easy.get(choice);
            for (int k = 1; k <= 9; k++) {
                for (int j = 1; j <= 9; j++) {
                    i = (k - 1) * 9 + j;
                    if (tmp.charAt(cnt) == '1') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/1_o.png")));
                    } else if (tmp.charAt(cnt) == '2') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/2_o.png")));
                    } else if (tmp.charAt(cnt) == '3') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/3_o.png")));
                    } else if (tmp.charAt(cnt) == '4') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/4_o.png")));
                    } else if (tmp.charAt(cnt) == '5') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5_o.png")));
                    } else if (tmp.charAt(cnt) == '6') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/6_o.png")));
                    } else if (tmp.charAt(cnt) == '7') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/7_o.png")));
                    } else if (tmp.charAt(cnt) == '8') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/8_o.png")));
                    } else if (tmp.charAt(cnt) == '9') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/9_o.png")));
                    } else if (tmp.charAt(cnt) == '0') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank.png")));
                    }
                    numberPanel[k][j] = tmp.charAt(cnt++) - '0';
                    if (numberPanel[k][j] > 0) {
                        numColor[k][j] = 1;
                    } else {
                        numColor[k][j] = 3;
                    }
                }
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    //加载中等题目
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Random ra = new Random();
        int len = Medium.size();
        if (len != 0) {
            int choice = ra.nextInt(1000000) % len;
            int cnt = 0;
            int i = 0;
            String tmp = Medium.get(choice);
            for (int k = 1; k <= 9; k++) {
                for (int j = 1; j <= 9; j++) {
                    i = (k - 1) * 9 + j;
                    if (tmp.charAt(cnt) == '1') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/1_o.png")));
                    } else if (tmp.charAt(cnt) == '2') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/2_o.png")));
                    } else if (tmp.charAt(cnt) == '3') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/3_o.png")));
                    } else if (tmp.charAt(cnt) == '4') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/4_o.png")));
                    } else if (tmp.charAt(cnt) == '5') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5_o.png")));
                    } else if (tmp.charAt(cnt) == '6') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/6_o.png")));
                    } else if (tmp.charAt(cnt) == '7') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/7_o.png")));
                    } else if (tmp.charAt(cnt) == '8') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/8_o.png")));
                    } else if (tmp.charAt(cnt) == '9') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/9_o.png")));
                    } else if (tmp.charAt(cnt) == '0') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank.png")));
                    }
                    numberPanel[k][j] = tmp.charAt(cnt++) - '0';
                    if (numberPanel[k][j] > 0) {
                        numColor[k][j] = 1;
                    } else {
                        numColor[k][j] = 3;
                    }
                }
            }
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    //加载难题
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Random ra = new Random();
        int len = Hard.size();
        if (len != 0) {
            int choice = ra.nextInt(1000000) % len;
            int cnt = 0;
            int i = 0;
            String tmp = Hard.get(choice);
            for (int k = 1; k <= 9; k++) {
                for (int j = 1; j <= 9; j++) {
                    i = (k - 1) * 9 + j;
                    if (tmp.charAt(cnt) == '1') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/1_o.png")));
                    } else if (tmp.charAt(cnt) == '2') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/2_o.png")));
                    } else if (tmp.charAt(cnt) == '3') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/3_o.png")));
                    } else if (tmp.charAt(cnt) == '4') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/4_o.png")));
                    } else if (tmp.charAt(cnt) == '5') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5_o.png")));
                    } else if (tmp.charAt(cnt) == '6') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/6_o.png")));
                    } else if (tmp.charAt(cnt) == '7') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/7_o.png")));
                    } else if (tmp.charAt(cnt) == '8') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/8_o.png")));
                    } else if (tmp.charAt(cnt) == '9') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/9_o.png")));
                    } else if (tmp.charAt(cnt) == '0') {
                        picBox[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank.png")));
                    }
                    numberPanel[k][j] = tmp.charAt(cnt++) - '0';
                    if (numberPanel[k][j] > 0) {
                        numColor[k][j] = 1;
                    } else {
                        numColor[k][j] = 3;
                    }
                }
            }
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    //单击重做按钮
    private void replayButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_replayButtonMouseClicked
        // TODO add your handling code here:
        //如果那个数字不是灰底黑字的块，那么就把它变成小灰块
        for (int i = 1; i <= 9; i++) {
            for (int j = 1; j <= 9; j++) {
                if (numColor[i][j] > 1 && numColor[i][j] <= 5) {
                    numColor[i][j] = 3;
                    numberPanel[i][j] = 0;
                    picBox[(i - 1) * 9 + j].setIcon(BlankLabel.getIcon());
                }
            }
        }
    }//GEN-LAST:event_replayButtonMouseClicked

    //单击清除按钮
    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        // TODO add your handling code here:
        for (int i = 1; i <= 9; i++) {
            for (int j = 1; j <= 9; j++) {
                if (numColor[i][j] == 5) {
                    numColor[i][j] = 4;
                    numberPanel[i][j] = 0;
                    picBox[(i - 1) * 9 + j].setIcon(SelectLabel.getIcon());
                }
            }
        }
    }//GEN-LAST:event_deleteButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    //初始化pictureBox
    private void InitPicBox() {
        picBox[1] = label1;
        picBox[2] = label2;
        picBox[3] = label3;
        picBox[4] = label4;
        picBox[5] = label5;
        picBox[6] = label6;
        picBox[7] = label7;
        picBox[8] = label8;
        picBox[9] = label9;
        picBox[10] = label10;
        picBox[11] = label11;
        picBox[12] = label12;
        picBox[13] = label13;
        picBox[14] = label14;
        picBox[15] = label15;
        picBox[16] = label16;
        picBox[17] = label17;
        picBox[18] = label18;
        picBox[19] = label19;
        picBox[20] = label20;
        picBox[21] = label21;
        picBox[22] = label22;
        picBox[23] = label23;
        picBox[24] = label24;
        picBox[25] = label25;
        picBox[26] = label26;
        picBox[27] = label27;
        picBox[28] = label28;
        picBox[29] = label29;
        picBox[30] = label30;
        picBox[31] = label31;
        picBox[32] = label32;
        picBox[33] = label33;
        picBox[34] = label34;
        picBox[35] = label35;
        picBox[36] = label36;
        picBox[37] = label37;
        picBox[38] = label38;
        picBox[39] = label39;
        picBox[40] = label40;
        picBox[41] = label41;
        picBox[42] = label42;
        picBox[43] = label43;
        picBox[44] = label44;
        picBox[45] = label45;
        picBox[46] = label46;
        picBox[47] = label47;
        picBox[48] = label48;
        picBox[49] = label49;
        picBox[50] = label50;
        picBox[51] = label51;
        picBox[52] = label52;
        picBox[53] = label53;
        picBox[54] = label54;
        picBox[55] = label55;
        picBox[56] = label56;
        picBox[57] = label57;
        picBox[58] = label58;
        picBox[59] = label59;
        picBox[60] = label60;
        picBox[61] = label61;
        picBox[62] = label62;
        picBox[63] = label63;
        picBox[64] = label64;
        picBox[65] = label65;
        picBox[66] = label66;
        picBox[67] = label67;
        picBox[68] = label68;
        picBox[69] = label69;
        picBox[70] = label70;
        picBox[71] = label71;
        picBox[72] = label72;
        picBox[73] = label73;
        picBox[74] = label74;
        picBox[75] = label75;
        picBox[76] = label76;
        picBox[77] = label77;
        picBox[78] = label78;
        picBox[79] = label79;
        picBox[80] = label80;
        picBox[81] = label81;

    }

    //初始化（灰底蓝字），出现的问题：注意picturebox的初始化，要new
    private void InitNumber_c() {
        for (int i = 0; i < 10; i++) {
            numC[i] = new JLabel();
        }
        numC[1].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/1_c.png")));
        numC[2].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/2_c.png")));
        numC[3].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/3_c.png")));
        numC[4].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/4_c.png")));
        numC[5].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5_c.png")));
        numC[6].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/6_c.png")));
        numC[7].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/7_c.png")));
        numC[8].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/8_c.png")));
        numC[9].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/9_c.png")));
    }

    //初始化（灰底黑字）
    private void InitNumber_o() {
        for (int i = 0; i < 10; i++) {
            numO[i] = new JLabel();
        }
        numO[1].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/1_o.png")));
        numO[2].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/2_o.png")));
        numO[3].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/3_o.png")));
        numO[4].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/4_o.png")));
        numO[5].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5_o.png")));
        numO[6].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/6_o.png")));
        numO[7].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/7_o.png")));
        numO[8].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/8_o.png")));
        numO[9].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/9_o.png")));
    }

    //初始化数字按钮
    private void InitButton() {
        buttonNum[1] = button1;
        buttonNum[2] = button2;
        buttonNum[3] = button3;
        buttonNum[4] = button4;
        buttonNum[5] = button5;
        buttonNum[6] = button6;
        buttonNum[7] = button7;
        buttonNum[8] = button8;
        buttonNum[9] = button9;
    }

    //初始化（蓝底黄字）
    private void InitButtonH() {
        for (int i = 0; i < 10; i++) {
            buttonNumH[i] = new JLabel();
        }
        buttonNumH[1].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/1_h.png")));
        buttonNumH[2].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/2_h.png")));
        buttonNumH[3].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/3_h.png")));
        buttonNumH[4].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/4_h.png")));
        buttonNumH[5].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5_h.png")));
        buttonNumH[6].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/6_h.png")));
        buttonNumH[7].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/7_h.png")));
        buttonNumH[8].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/8_h.png")));
        buttonNumH[9].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/9_h.png")));
    }

    //初始化（蓝底白字）
    private void InitButtonO() {
        for (int i = 0; i < 10; i++) {
            buttonNumO[i] = new JLabel();
        }
        buttonNumO[1].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/1_b.png")));
        buttonNumO[2].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/2_b.png")));
        buttonNumO[3].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/3_b.png")));
        buttonNumO[4].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/4_b.png")));
        buttonNumO[5].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5_b.png")));
        buttonNumO[6].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/6_b.png")));
        buttonNumO[7].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/7_b.png")));
        buttonNumO[8].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/8_b.png")));
        buttonNumO[9].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/9_b.png")));
    }

    //将需要的图片放入内存
    private void InitLabel() {
        BlankLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank.png")));
        SelectLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blank_s.png")));
        wrongLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/wrong.png")));
        correctLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/correct.png")));
    }

    //初始化简单题目
    private void InitEasyQ() {
        readFileByLines("/Q_A/Easy.txt", Easy);
    }

    //初始化中等题目
    private void InitMediumQ() {
        readFileByLines("/Q_A/Medium.txt", Medium);
    }

    //初始化难题
    private void InitHardQ() {
        readFileByLines("/Q_A/Hard.txt", Hard);
    }

    //按行读取文件
    public static void readFileByLines(String path, ArrayList a) {
        try {
            BufferedReader bf = new BufferedReader(new InputStreamReader(MainFrame.class.getResource(path).openStream()));
            String str;
            while ((str = bf.readLine()) != null) {
                a.add(str);
            }
        } catch (IOException e) {
        }
    }

    //判断是否正确
    private boolean isRight(int x, int y) {
        int loc_x = x;//获取当前picbox的位置
        int loc_y = y;

        //找出当前所表示的数字
        int num = numberPanel[loc_x][loc_y];

        //找出行正确性
        for (int n = 1; n <= 9; n++) {
            if (n == loc_y) {
                continue;
            } else if (numberPanel[loc_x][n] == num) {
                return false;
            }
        }

        //检验所在列的正确性
        for (int n = 1; n <= 9; n++) {
            if (n == loc_x) {
                continue;
            } else if (numberPanel[n][loc_y] == num) {
                return false;
            }
        }

        //检验所在小方块中的正确性
        int k = (loc_x - 1) / 3 * 3 + 1;//3*3的小区域的行坐标
        int j = (loc_y - 1) / 3 * 3 + 1;//3*3的小区域的列坐标
        for (int m = k; m < k + 3; m++) {
            for (int n = j; n < j + 3; n++)//循环遍历3*3小区域
            {
                if (m == loc_x && n == loc_y) {
                    continue;
                } else if (numberPanel[m][n] == num) {
                    return false;
                }
            }
        }
        return true;
    }

    //判断游戏输赢
    private boolean win() {
        //没有灰色的空，没有蓝色的空，没有灰色的空，没有w的
        for (int i = 1; i <= 9; i++) {
            for (int j = 1; j <= 9; j++) {
                if (numColor[i][j] == 3 || numColor[i][j] == 4) {
                    return false;
                }
            }
        }
        return true;
    }

    private void blocksAddListener() {
        for (int i = 1; i < picBox.length; i++) {
            JLabel curSelectLabel = picBox[i];
            int loc = i;
            picBox[i].addMouseListener(new MouseAdapter() {
                @Override//点击事件数字panel中的
                public void mouseClicked(MouseEvent e) {
                    int x = (loc - 1) / 9 + 1;
                    int y = loc % 9;
                    if (y == 0) {
                        y = 9;
                    }
                    if (numColor[x][y] == 3) {
                        for (int i = 1; i <= 9; i++) {
                            for (int j = 1; j <= 9; j++) {
                                if (numColor[i][j] == 4) {
                                    picBox[(i - 1) * 9 + j].setIcon(BlankLabel.getIcon());
                                    numColor[i][j] = 3;
                                } else if (numColor[i][j] == 5) {
                                    picBox[(i - 1) * 9 + j].setIcon(numC[numberPanel[i][j]].getIcon());
                                    numColor[i][j] = 2;
                                }
                            }
                        }
                        numColor[x][y] = 4;
                        curSelectLabel.setIcon(SelectLabel.getIcon());
                    } else if (numColor[x][y] == 2) {
                        for (int i = 1; i <= 9; i++) {
                            for (int j = 1; j <= 9; j++) {
                                if (numColor[i][j] == 4) {
                                    picBox[(i - 1) * 9 + j].setIcon(BlankLabel.getIcon());
                                    numColor[i][j] = 3;
                                } else if (numColor[i][j] == 5) {
                                    picBox[(i - 1) * 9 + j].setIcon(numC[numberPanel[i][j]].getIcon());
                                    numColor[i][j] = 2;
                                }
                            }
                        }
                        if (numColor[x][y] == 1) {
                        } else if (numColor[x][y] > 0) {
                            numColor[x][y] = 5;
                            curSelectLabel.setIcon(buttonNumO[numberPanel[x][y]].getIcon());
                        } else if (numColor[x][y] < 9) {
                            numColor[x][y] = 4;
                            curSelectLabel.setIcon(SelectLabel.getIcon());
                        }
                    }
                }
            });
        }

        for (int i = 1; i < buttonNum.length; i++) {
            JLabel curSelectLabel = buttonNum[i];
            JLabel label1 = buttonNumH[i];
            JLabel label2 = buttonNumO[i];
            int curLoc = i;
            buttonNum[i].addMouseListener(new MouseAdapter() {
                @Override//选择盘的点击事件
                public void mouseClicked(MouseEvent e) {
                    int x = 0, y = 0;
                    for (int i = 1; i <= 9; i++) {
                        for (int j = 1; j <= 9; j++) {
                            if (numColor[i][j] == 4 || numColor[i][j] == 5) {
                                x = i;
                                y = j;
                                picBox[(i - 1) * 9 + j].setIcon(buttonNumO[curLoc].getIcon());
                                numberPanel[i][j] = curLoc;
                                numColor[i][j] = 5;
                                i += 9;
                                j += 9;
                            }
                        }
                    }
                    if (x == 0 || y == 0) {
                        return;
                    } else if (!isRight(x, y)) {
                        picBox[(x - 1) * 9 + y].setIcon(SelectLabel.getIcon());
                        numberPanel[x][y] = 0;
                        numColor[x][y] = 4;

                        checkLabel.setIcon(wrongLabel.getIcon());

                    } else {
                        checkLabel.setIcon(correctLabel.getIcon());
                    }
                    if (win()) {
                        JOptionPane.showMessageDialog(getContentPane(), "恭喜你！你赢了！！！！", "系统信息", JOptionPane.INFORMATION_MESSAGE);
                    }
                }

                @Override//鼠标进入按钮
                public void mouseEntered(MouseEvent e) {
                    curSelectLabel.setIcon(label1.getIcon());
                }

                @Override//鼠标离开按钮
                public void mouseExited(MouseEvent e) {
                    curSelectLabel.setIcon(label2.getIcon());
                }
            });
        }

    }

    //声明的变量
    private JLabel[] picBox = new JLabel[82];//数字面板
    private JLabel[] buttonNum = new JLabel[10];//数字选择
    private JLabel[] numC = new JLabel[10];//灰底蓝字
    private JLabel[] numO = new JLabel[10];//灰底黑字
    private JLabel[] buttonNumH = new JLabel[10];//蓝底黄字
    private JLabel[] buttonNumO = new JLabel[10];//蓝底白字
    private int[][] numberPanel = new int[10][10];//记录数字盘上的数字
    private int[][] numColor = {{9, 9, 9, 9, 9, 9, 9, 9, 9, 9}, {9, 9, 9, 9, 9, 9, 9, 9, 9, 9}, {9, 9, 9, 9, 9, 9, 9, 9, 9, 9}, {9, 9, 9, 9, 9, 9, 9, 9, 9, 9},
    {9, 9, 9, 9, 9, 9, 9, 9, 9, 9}, {9, 9, 9, 9, 9, 9, 9, 9, 9, 9}, {9, 9, 9, 9, 9, 9, 9, 9, 9, 9}, {9, 9, 9, 9, 9, 9, 9, 9, 9, 9}, {9, 9, 9, 9, 9, 9, 9, 9, 9, 9}, {9, 9, 9, 9, 9, 9, 9, 9, 9, 9}};
    //记录数字的style种类，1.灰底黑字，2.灰底蓝字，3.灰框，4.蓝框，5.蓝底白字
    private int[] controlPanel = new int[10];//记录数字选择框的数字
    private ArrayList<String> Easy = new ArrayList<String>();//用来存放简单题目
    private ArrayList<String> Medium = new ArrayList<String>();//用来存放中等题目
    private ArrayList<String> Hard = new ArrayList<String>();//用来存放难题
    private ArrayList<String> Test = new ArrayList<String>();//用来存放难题
    private JLabel BlankLabel = new JLabel();//装灰底空
    private JLabel SelectLabel = new JLabel();//装蓝底空
    private JLabel correctLabel = new JLabel();//装笑脸
    private JLabel wrongLabel = new JLabel();//装哭脸


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel button1;
    private javax.swing.JLabel button2;
    private javax.swing.JLabel button3;
    private javax.swing.JLabel button4;
    private javax.swing.JLabel button5;
    private javax.swing.JLabel button6;
    private javax.swing.JLabel button7;
    private javax.swing.JLabel button8;
    private javax.swing.JLabel button9;
    private javax.swing.JLabel checkLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label13;
    private javax.swing.JLabel label14;
    private javax.swing.JLabel label15;
    private javax.swing.JLabel label16;
    private javax.swing.JLabel label17;
    private javax.swing.JLabel label18;
    private javax.swing.JLabel label19;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label20;
    private javax.swing.JLabel label21;
    private javax.swing.JLabel label22;
    private javax.swing.JLabel label23;
    private javax.swing.JLabel label24;
    private javax.swing.JLabel label25;
    private javax.swing.JLabel label26;
    private javax.swing.JLabel label27;
    private javax.swing.JLabel label28;
    private javax.swing.JLabel label29;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label30;
    private javax.swing.JLabel label31;
    private javax.swing.JLabel label32;
    private javax.swing.JLabel label33;
    private javax.swing.JLabel label34;
    private javax.swing.JLabel label35;
    private javax.swing.JLabel label36;
    private javax.swing.JLabel label37;
    private javax.swing.JLabel label38;
    private javax.swing.JLabel label39;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label40;
    private javax.swing.JLabel label41;
    private javax.swing.JLabel label42;
    private javax.swing.JLabel label43;
    private javax.swing.JLabel label44;
    private javax.swing.JLabel label45;
    private javax.swing.JLabel label46;
    private javax.swing.JLabel label47;
    private javax.swing.JLabel label48;
    private javax.swing.JLabel label49;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label50;
    private javax.swing.JLabel label51;
    private javax.swing.JLabel label52;
    private javax.swing.JLabel label53;
    private javax.swing.JLabel label54;
    private javax.swing.JLabel label55;
    private javax.swing.JLabel label56;
    private javax.swing.JLabel label57;
    private javax.swing.JLabel label58;
    private javax.swing.JLabel label59;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label60;
    private javax.swing.JLabel label61;
    private javax.swing.JLabel label62;
    private javax.swing.JLabel label63;
    private javax.swing.JLabel label64;
    private javax.swing.JLabel label65;
    private javax.swing.JLabel label66;
    private javax.swing.JLabel label67;
    private javax.swing.JLabel label68;
    private javax.swing.JLabel label69;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label70;
    private javax.swing.JLabel label71;
    private javax.swing.JLabel label72;
    private javax.swing.JLabel label73;
    private javax.swing.JLabel label74;
    private javax.swing.JLabel label75;
    private javax.swing.JLabel label76;
    private javax.swing.JLabel label77;
    private javax.swing.JLabel label78;
    private javax.swing.JLabel label79;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label80;
    private javax.swing.JLabel label81;
    private javax.swing.JLabel label9;
    private javax.swing.JButton replayButton;
    // End of variables declaration//GEN-END:variables

}
